food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:item_id>/',views.detail,name='detail'),
    path('add',views.create_item,name='create_item'),
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name = 'users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name = 'users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile')
]


urlpatterns += [

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://platerate.com/images/tempfoodnotext.png")

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default = 'profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)


def __str__(self):
    return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from.models import Item
from django.template import loader
from .forms import ItemForm

def index(request):
    item_list = Item.objects.all()
    template = loader.get_template('food/index.html')
    context = {
        'item_list':item_list,
    }
    return HttpResponse(template.render(context,request))

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request,'food/detail.html',context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form})

def update_item(request,id):
    item = Item.objects.get(id=id)

    form = ItemForm(request.POST or None,instance = item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id = id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import redirect,render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm

def register(request):
    form_class = RegisterForm
    form = form_class(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'welcome {username},your account has created successfully')
            return redirect('login')

        else:
            form = form_class()
    return render (request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{%load static %}
<!DOCTYPE html>
<html>

   <head>
      <title>Django POC App</title>
      <link rel="stylesheet" href="{% static 'food.style.css' %}">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   </head>
	
   <body>
       <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Food App</a>

        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item nav-link" href="#">Delete Item</a>
            <a class="nav-item nav-link" href="#">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div>
       </nav>
        {% if messages %}
                {% for message in messages %}
                    <div class="alert alert--{{ message.tags }}">
                        {{message}}
                    </div>
                {% endfor %}
        {% endif %}

       {% block body %}
       {% endblock %}

   </body>
	
</html>

food/templates/food/detail.html
{% extends  'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{item.item_image}}" height="200px" class="card"/>
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <h2> {{ item.item_desc}}</h2>
            <h3> ${{ item.item_price}}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>


{% endblock %}

food/templates/food/index.html
{% extends  'food/base.html' %}
<!DOCTYPE html>
<html>

   <head>
      <title>Django POC App</title>
      <meta charset="utf-8">
      <meta http-equiv = "Content-Type" content = "text/html; charset = UTF-8" />
      
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   </head>
	
   <body>
    {% block body %}

    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{item.item_image}}" />
            </div>
            <div class="col-md-4">
                <h3> {{ item.item_name }}</h3>
                <h5> {{ item.item_desc}}</h5>
                <h6>${{ item.item_price}}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        {% endfor %}
        {% endblock %}
        <ul>
            <li>
                <a href="">{{ item.id}} -- {{item.item_name}}</a>
            </li>
        </ul>

   </body>
	
</html>

food/templates/food/item-delete.html
{% extends  'food/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    <h2>Are you sure u want to delete {{item.item_name}}</h2>
    <button type="submit">Conform</button>
</form>

{% endblock %}

food/templates/food/item-form.html
{% extends  'food/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">save</button>
</form>

{% endblock %}

users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Login</button>
</form>

users/templates/users/logout.html
<form method="POST">
    {% csrf_token %}
    {{form}}
    <h2>You have been logged out</h2>
</form>

users/templates/users/profile.html
<h1>{{user.username}}</h1>

<img src="{{ user.profile.image.url }}" >

users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">signup</button>
</form>